name: Test, Build and Deploy

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

            - name: Run unit tests
              run: npm run test

            - name: Run test coverage
              run: npm run test:cov

            - name: Run e2e tests
              run: npm run test:e2e

    build:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    test-commands:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Create test file
              run: |
                  echo -e "line1\nline2\nline3\nline4\nline5\nline6\nline7\nline8\nline9\nline10\nline11\nline12" > test_input.txt

            - name: Test head command (5 lines)
              run: npm run start:prod -- head test_input.txt -n 5

            - name: Test head command (default 10 lines)
              run: npm run start:prod -- head test_input.txt

            - name: Create duplicate test file
              run: |
                  echo -e "apple\napple\nbanana\nbanana\nbanana\ncherry\ncherry" > test_duplicates.txt

            - name: Test uniq command
              run: npm run start:prod -- uniq test_duplicates.txt

            - name: Test uniq with count
              run: npm run start:prod -- uniq test_duplicates.txt -c

            - name: Test uniq with duplicates only
              run: npm run start:prod -- uniq test_duplicates.txt -d

            - name: Test uniq with unique only
              run: npm run start:prod -- uniq test_duplicates.txt -u

    deploy:
        needs: [build, test-commands]
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Setup NPM authentication
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
                  chmod 600 ~/.npmrc

            - name: Publish to NPM
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ github.run_number }}
                  release_name: Release v${{ github.run_number }}
                  body: |
                      Automated release from GitHub Actions

                      - Published to NPM: @rostyslavpasternak/lab-2
                      - Build artifacts available in Actions
                  draft: false
                  prerelease: false
