name: Release & Publish

on:
    push:
        branches:
            - main

permissions:
    contents: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org/"
                  scope: "@mindlet"
                  always-auth: true

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Bump version & publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  npm version patch -m "chore(release): v%s"
                  npm publish --access public
                  git push origin main --follow-tags
